In [ ]:
# only if you get an error from below
# from pystatis import init_config
# init_config()

In [3]:
import logging
logging.basicConfig(level=logging.INFO)

import pandas as pd

from pystatis.cube import parse_cube, rename_axes
from pystatis.http_helper import get_data_from_endpoint

## Download a cube file

The `get_cubefile()` function will download the cube as csv cubefile and return the data as string.

In [5]:
params = {"name": "47414BJ002", "area": "all", "values": "true", "metadata": "true", "additionals": "false"}
data = get_data_from_endpoint("data", "cubefile", params)

In [6]:
type(data), len(data)

(str, 84324)

In [7]:
data.splitlines()[:20]

['* Der Benutzer DEI6I4B3UW der Benutzergruppe DE0142 hat am 16.09.2022 um 23:24:58 diesen Export angestossen.',
 'K;DQ;FACH-SCHL;GHH-ART;GHM-WERTE-JN;GENESIS-VBD;REGIOSTAT;EU-VBD;"mit Werten"',
 'D;47414BJ002;;N;N;N;N',
 'K;DQ-ERH;FACH-SCHL',
 'D;47414',
 'K;DQA;NAME;RHF-BSR;RHF-ACHSE',
 'D;DINSG;1;1',
 'D;WZ08N7;2;2',
 'D;WERTE4;3;3',
 'K;DQZ;NAME;ZI-RHF-BSR;ZI-RHF-ACHSE',
 'D;JAHR;4;4',
 'K;DQI;NAME;ME-NAME;DST;TYP;NKM-STELLEN;GHH-ART;GHM-WERTE-JN',
 'D;UMS103;2015=100;FEST;PROZENT;1;;N',
 'K;QEI;FACH-SCHL;FACH-SCHL;FACH-SCHL;ZI-WERT;WERT;QUALITAET;GESPERRT;WERT-VERFAELSCHT',
 'D;DG;WZ08-49-01;NOMINAL;2015;100.0;e;;0.0',
 'D;DG;WZ08-49-01;NOMINAL;2016;99.3;e;;0.0',
 'D;DG;WZ08-49-01;NOMINAL;2017;105.7;e;;0.0',
 'D;DG;WZ08-49-01;NOMINAL;2018;111.6;e;;0.0',
 'D;DG;WZ08-49-01;NOMINAL;2019;115.6;e;;0.0',
 'D;DG;WZ08-49-01;NOMINAL;2020;96.0;e;;0.0']

## Parsing the cube file

The `parse_cube(data)` function can parse the raw string and return a dictionary with the different headers and the data section. Data is stored as pandas `DataFrame`.

In [8]:
cube = parse_cube(data)

In [9]:
cube

{'DQ':     FACH-SCHL GHH-ART GHM-WERTE-JN GENESIS-VBD REGIOSTAT EU-VBD
 0  47414BJ002                    N           N         N      N,
 'DQ-ERH':   FACH-SCHL
 0     47414,
 'DQA':      NAME RHF-BSR RHF-ACHSE
 0   DINSG       1         1
 1  WZ08N7       2         2
 2  WERTE4       3         3,
 'DQZ':    NAME ZI-RHF-BSR ZI-RHF-ACHSE
 0  JAHR          4            4,
 'DQI':      NAME   ME-NAME   DST      TYP NKM-STELLEN GHH-ART GHM-WERTE-JN
 0  UMS103  2015=100  FEST  PROZENT           1                    N,
 'QEI':      FACH-SCHL-1 FACH-SCHL-2 FACH-SCHL-3 ZI-WERT UMS103_WERT UMS103_QUALITAET  \
 0             DG  WZ08-49-01     NOMINAL    2015       100.0                e
 1             DG  WZ08-49-01     NOMINAL    2016        99.3                e
 2             DG  WZ08-49-01     NOMINAL    2017       105.7                e
 3             DG  WZ08-49-01     NOMINAL    2018       111.6                e
 4             DG  WZ08-49-01     NOMINAL    2019       115.6                e
 ...          ...         ...         ...     ...         ...              ...
 2151          DG      WZ08-N        REAL    2017       108.4                e
 2152          DG      WZ08-N        REAL    2018       110.6                e
 2153          DG      WZ08-N        REAL    2019       110.8                e
 2154          DG      WZ08-N        REAL    2020        94.1                e
 2155          DG      WZ08-N        REAL    2021       101.2                p

      UMS103_GESPERRT UMS103_WERT-VERFAELSCHT
 0                                        0.0
 1                                        0.0
 2                                        0.0
 3                                        0.0
 4                                        0.0
 ...              ...                     ...
 2151                                     0.0
 2152                                     0.0
 2153                                     0.0
 2154                                     0.0
 2155                                     0.0

 [2156 rows x 8 columns]}

In [10]:
cube["QEI"]

,FACH-SCHL-1,FACH-SCHL-2,FACH-SCHL-3,ZI-WERT,UMS103_WERT,UMS103_QUALITAET,UMS103_GESPERRT,UMS103_WERT-VERFAELSCHT
0,DG,WZ08-49-01,NOMINAL,2015,100.0,e,,0.0
1,DG,WZ08-49-01,NOMINAL,2016,99.3,e,,0.0
2,DG,WZ08-49-01,NOMINAL,2017,105.7,e,,0.0
3,DG,WZ08-49-01,NOMINAL,2018,111.6,e,,0.0
4,DG,WZ08-49-01,NOMINAL,2019,115.6,e,,0.0
...,...,...,...,...,...,...,...,...
2151,DG,WZ08-N,REAL,2017,108.4,e,,0.0
2152,DG,WZ08-N,REAL,2018,110.6,e,,0.0
2153,DG,WZ08-N,REAL,2019,110.8,e,,0.0
2154,DG,WZ08-N,REAL,2020,94.1,e,,0.0
2155,DG,WZ08-N,REAL,2021,101.2,p,,0.0

In [11]:
cube["DQA"]

     NAME RHF-BSR RHF-ACHSE
0   DINSG       1         1
1  WZ08N7       2         2
2  WERTE4       3         3

## Renaming Axes

The `rename_axes(cube)` function can rename the columns of a data frame according to the metadata delivered with the cube file. `cube` has to be a dictionary as is returned by `parse_cube()`.

In [12]:
rename_axes(cube)["QEI"]

,DINSG,WZ08N7,WERTE4,JAHR,UMS103_WERT,UMS103_QUALITAET,UMS103_GESPERRT,UMS103_WERT-VERFAELSCHT
0,DG,WZ08-49-01,NOMINAL,2015,100.0,e,,0.0
1,DG,WZ08-49-01,NOMINAL,2016,99.3,e,,0.0
2,DG,WZ08-49-01,NOMINAL,2017,105.7,e,,0.0
3,DG,WZ08-49-01,NOMINAL,2018,111.6,e,,0.0
4,DG,WZ08-49-01,NOMINAL,2019,115.6,e,,0.0
...,...,...,...,...,...,...,...,...
2151,DG,WZ08-N,REAL,2017,108.4,e,,0.0
2152,DG,WZ08-N,REAL,2018,110.6,e,,0.0
2153,DG,WZ08-N,REAL,2019,110.8,e,,0.0
2154,DG,WZ08-N,REAL,2020,94.1,e,,0.0
2155,DG,WZ08-N,REAL,2021,101.2,p,,0.0

In [13]:
rename_axes(cube)["QEI"]["JAHR"].unique()

array(['2015', '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype=object)